#!/usr/bin/env bash

set -eu

ROOT_DIR="$(pwd)"

prepare_build_dir() {
    if ! [ -d "./build" ]; then
        mkdir "./build"
    fi
}

clone_repo() {
    CLONE_URL="$1"
    BRANCH="${2:-main}"
    DESTINATION="./build/$3"

    if [ -d "$DESTINATION" ]; then
        echo -e "\n$DESTINATION exists, pulling..."
        cd "$DESTINATION"
        git pull
        cd - >/dev/null
    else
        echo -e "\ncloning $CLONE_URL"
        git clone --branch "$BRANCH" "$CLONE_URL" "$DESTINATION"
    fi
}

flare_system_c_chain_indexer() {
    clone_repo "https://github.com/flare-foundation/flare-system-c-chain-indexer.git" \
        "$FLARE_SYSTEM_C_INDEXER_BRANCH" \
        "flare-system-c-chain-indexer"
}

flare_system_client() {
    clone_repo "https://github.com/flare-foundation/flare-system-client.git" \
        "$FLARE_SYSTEM_CLIENT_BRANCH" \
        "flare-system-client/"
}

ftso_scaling() {
    clone_repo "https://github.com/flare-foundation/ftso-scaling.git" \
        "$FTSO_SCALING_BRANCH" \
        "ftso-scaling/"
}

main() {
    source <(grep -v '^#' "./.env" | sed -E 's|^(.+)=(.*)$|: ${\1=\2}; export \1|g')

    case "${1}" in
    clean)
        rm -rf "./build"
        ;;
    pull)
        echo "pulling repositories"
        prepare_build_dir
        flare_system_c_chain_indexer
        flare_system_client
        ftso_scaling
        ;;
    *)
        return 1
        ;;
    esac
}

main "$@"
